[package]
name = "dbc-codegen"
version = "0.1.0"
authors = ["Pascal Hertleif <pascal@technocreatives.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.33"
can-dbc = "3.0.2"
heck = "0.3.1"
structopt = "0.3.20"

[workspace]
members = [
    ".",
    "testing/rust-integration",
    "testing/can-messages",
]
