[package]
name = "can-embedded"
version = "0.1.0"
authors = ["Pascal Hertleif <pascal@technocreatives.com>"]
edition = "2018"

[dependencies]
bitvec = { version = "0.21", default-features = false }
float-cmp = "0.8"

[features]
debug = []
range_checked = []
