[package]
name = "dbc-codegen-cli"
version = "0.1.0"
authors = ["Pascal Hertleif <pascal@technocreatives.com>"]
edition = "2018"

[dependencies]
heck = "0.3.1"
structopt = "0.3.20"
exitcode = "1.1.2"
dbc-codegen = { path = ".." }

[[bin]]
name = "dbc-codegen"
path = "src/main.rs"
